// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt15oxAuGqf6S_bmtq4UUIbGhN63s526A',
    appId: '1:915529495225:web:77db15a567c773b9572168',
    messagingSenderId: '915529495225',
    projectId: 'medical-app-301d6',
    authDomain: 'medical-app-301d6.firebaseapp.com',
    storageBucket: 'medical-app-301d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJFLCcQp5n2AnGQyCsciEQ1aHMS07wPY',
    appId: '1:915529495225:android:f509d68d67b827e5572168',
    messagingSenderId: '915529495225',
    projectId: 'medical-app-301d6',
    storageBucket: 'medical-app-301d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQxKbEkj1OHcsjDlphXdUdT--ALocots',
    appId: '1:915529495225:ios:52031af81fee87b6572168',
    messagingSenderId: '915529495225',
    projectId: 'medical-app-301d6',
    storageBucket: 'medical-app-301d6.appspot.com',
    iosClientId: '915529495225-k6k4djejqe053ju7u936e4f8ul8b43tt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQxKbEkj1OHcsjDlphXdUdT--ALocots',
    appId: '1:915529495225:ios:52031af81fee87b6572168',
    messagingSenderId: '915529495225',
    projectId: 'medical-app-301d6',
    storageBucket: 'medical-app-301d6.appspot.com',
    iosClientId: '915529495225-k6k4djejqe053ju7u936e4f8ul8b43tt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApp',
  );
}
